import React, { useState } from "react";
import { FaExclamationCircle } from "react-icons/fa";
import { API_URL } from "../../../Global";
import { Link } from "react-router-dom";
export default function ForgotPassword() {
	const [email, setEmail] = useState("");
	const [emailError, setEmailError] = useState("");

	const sendMessage = (e) => {
		e.preventDefault();
		const data = {
			registerEmail: email,
		};
		if (validateFields()) {
			fetch(`${API_URL}ForgetPassword`, {
				method: "POST",
				headers: {
					"Content-Type": "application/json",
				},
				body: JSON.stringify(data),
			})
				.then((response) => response.json())
				.then((jsonResponse) => {
					console.log("Success: ", jsonResponse);
					const error = jsonResponse.error;
					if (
						error ===
						"The email address that you have, doesn't match with any registered email."
					) {
						setEmailError("Invalid Email");
					}
				})
				.catch((error) => console.log("Error: ", error));
		}
	};
	const validateFields = () => {
		let is_valid = true;
		const reg = /^[a-zA-Z0-9]+@(?:[a-zA-Z0-9]+\.)+[A-Za-z]+$/;
		if (!email) {
			setEmailError("Email cannot be empty");
			is_valid = false;
		} else if (!reg.test(email)) {
			setEmailError("Invalid Email");
			is_valid = false;
		} else setEmailError("");
		return is_valid;
	};

	return (
		<section className="hero-section">
			<div className="hero-section-bg d-flex align-items-center">
				<div className="container">
					<div className="row d-flex align-items-center">
						<div className="col-xl-7 col-lg-12 col-md-12 text-xl-left text-center order-xl-1 order-2">
							<div className="my-5">
								<div className="">
									<h1 className="hero-section-heading">
										<span className="font-weight-bold font-4">
											Let's Use Data
											<br />
											to Improve your
											<br />
											Learning Experience
										</span>
									</h1>
								</div>
							</div>
						</div>

						<div className="col-xl-5 col-lg-12 col-md-12 text-xl-right text-center order-xl-2 order-1">
							<form className="login-card my-5" onSubmit={sendMessage}>
								<h4 className="mb-3" style={{ fontWeight: "600" }}>
									Forgot Your Password?
								</h4>
								<span style={{ lineHeight: "20px", color: "#4A4A4A" }}>
									Enter your registered email address. We’ll send you an email
									with a new autogenerated password.
								</span>

								<div className="form-group mt-4">
									<input
										id="TextBoxRegisterEmail"
										type="text"
										className="form-control custom-input"
										placeholder="Your Email Address"
										onChange={(e) => setEmail(e.target.value)}
									/>
									{emailError && (
										<div className="input-validation-message">
											<FaExclamationCircle /> {emailError}
										</div>
									)}
								</div>
								<div className="pt-5 mb-3">
									<input
										type="submit"
										className="btn custom-primary-btn"
										value="Submit"
										id="ForgetPasswordbtn"
										onClick={sendMessage}
									/>
								</div>
								<div className="text-center">
									<Link to="/login" className="login-card_quick-link">
										Back to Login
									</Link>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</section>
	);
}
